platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-orca/clang-toolchain
    tag: 0.2

inputs:
  - name: gpdb_src
    path: .
run:
  path: sh
  args:
  - -exc
  - |
    CXX=clang++-11 cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja -DCMAKE_BUILD_TYPE=Debug -Hsrc/backend/gporca -Bbuild.debug
    src/tools/tidy chk build.debug
    CXX=clang++-11 cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -Hsrc/backend/gporca -Bbuild.relwithdebinfo
    src/tools/tidy chk build.relwithdebinfo
params:
  CLANG_TIDY: clang-tidy-11
